// AUTH
export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER";

// COMMON REDUCER
export const IS_FETCHING = "IS_FETCHING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

// FORM REDUCER
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";

// EMAILS
export const SET_EMAILS = "SET_EMAILS";
export const SET_EMAIL = "SET_EMAIL";
export const SET_EMAIL_QUERY = "SET_EMAIL_QUERY";
export const CLEAR_EMAILS = "CLEAR_EMAILS";
export const CLEAR_EMAIL = "CLEAR_EMAIL";
export const SET_EMAIL_SEARCH = "SET_EMAIL_SEARCH";
export const SET_EMAILS_BY_CONTACT = "SET_EMAILS_BY_CONTACT";

// CONTACTS
export const SET_CONTACTS = "SET_CONTACTS";
export const SET_CONTACT = "SET_CONTACT";
export const SET_CONTACT_LISTINGS = "SET_CONTACT_LISTINGS";
export const SET_CONTACT_GROUPS = "SET_CONTACT_GROUPS";
export const SET_CONTACT_IMAGES = "SET_CONTACT_IMAGES";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const CLEAR_CONTACT = "CLEAR_CONTACT";
// export const CLEAR_EMAILS_BY_CONTACT = "CLEAR_EMAILS_BY_CONTACT";

// LISTINGS
export const SET_LISTING = "SET_LISTING";
export const SET_LISTINGS = "SET_LISTINGS";
export const SET_LISTING_SEARCH = "SET_LISTING_SEARCH";
export const SET_LISTING_IMAGES = "SET_LISTING_IMAGES";
export const SET_EMAILS_BY_LISTING = "SET_EMAILS_BY_LISTING";
export const IS_LISTING_NEW = "IS_LISTING_NEW";
export const CLEAR_LISTING = "CLEAR_LISTING";
export const CLEAR_LISTINGS = "CLEAR_LISTINGS";
export const SET_LISTING_QUERY = "SET_LISTING_QUERY";

// LISTING CONTACTS
export const SET_LISTING_CONTACTS = "SET_LISTING_CONTACTS";
export const SET_LISTING_CONTACTS_SEARCH_RESULTS =
  "SET_LISTING_CONTACTS_SEARCH_RESULTS";
export const CLEAR_LISTING_CONTACTS_SEARCH_RESULTS =
  "CLEAR_LISTING_CONTACTS_SEARCH_RESULTS";
export const DELETE_LISTING_CONTACT = "DELETE_LISTING_CONTACT";

// CONTACT LISTINGS
export const SET_CONTACT_LISTINGS_SEARCH_RESULTS =
  "SET_CONTACT_LISTINGS_SEARCH_RESULTS";
export const CLEAR_CONTACT_LISTINGS_SEARCH_RESULTS =
  "CLEAR_CONTACT_LISTINGS_SEARCH_RESULTS";

// GROUPS
export const SET_GROUPS = "SET_GROUPS";
export const SET_GROUP = "SET_GROUP";
export const CLEAR_GROUPS = "CLEAR_GROUPS";

// GROUP CONTACTS
export const SET_GROUP_CONTACTS = "SET_GROUP_CONTACTS";
export const CLEAR_GROUP_CONTACTS = "CLEAR_GROUP_CONTACTS";
export const SET_GROUP_ID = "SET_GROUP_ID";
export const SET_GROUP_CONTACTS_SEARCH_RESULTS =
  "SET_GROUP_CONTACTS_SEARCH_RESULTS";
export const CLEAR_GROUP_CONTACTS_SEARCH_RESULTS =
  "CLEAR_GROUP_CONTACTS_SEARCH_RESULTS";
export const SET_GROUP_CONTACTS_COMPONENT = "SET_GROUP_CONTACTS_COMPONENT";
export const SET_SELECTED_CONTACTS = "SET_SELECTED_CONTACTS";

// CAMPAIGNS:
export const SET_CAMPAIGN = "SET_CAMPAIGN";
export const SET_CAMPAIGNS = "SET_CAMPAIGNS";

// CAMPAIGN LISTINGS:
export const SET_CAMPAIGN_LISTINGS = "SET_CAMPAIGN_LISTINGS";
export const SET_CAMPAIGN_LISTINGS_SEARCH_RESULTS =
  "SET_CAMPAIGN_LISTINGS_SEARCH_RESULTS";
export const CLEAR_CAMPAIGN_LISTINGS_SEARCH_RESULTS =
  "CLEAR_CAMPAIGN_LISTINGS_SEARCH_RESULTS";

// CAMPAIGN GROUPS:
export const SET_CAMPAIGN_GROUPS = "SET_CAMPAIGN_GROUPS";
export const SET_CAMPAIGN_GROUPS_SEARCH_RESULTS =
  "SET_CAMPAIGN_GROUPS_SEARCH_RESULTS";
export const CLEAR_CAMPAIGN_GROUPS_SEARCH_RESULTS =
  "CLEAR_CAMPAIGN_GROUPS_SEARCH_RESULTS";

// MODAL REDUCER
export const SET_MODAL_VISIBILITY = "SET_MODAL_VISIBILITY";

// QUERY REDUCER:
export const SET_COUNT = "SET_COUNT";
export const RESET_QUERY = "RESET_QUERY";
export const SET_OFFSET = "SET_OFFSET";
export const SET_QUERY = "SET_QUERY";
export const IS_LOADING = "IS_LOADING";
