// AUTH
export const AUTH_USER = "AUTH_USER";
export const UNAUTH_USER = "UNAUTH_USER";

// COMMON REDUCER
export const IS_FETCHING = "IS_FETCHING";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const CLEAR_FORM_DATA = "CLEAR_FORM_DATA";

// MODAL REDUCER
export const SET_SELECTED = "SET_SELECTED";

// NAV REDUCER
export const SET_ACTIVE_KEY = "SET_ACTIVE_KEY";

// QUERY REDUCER:
export const SET_COUNT = "SET_COUNT";
export const SET_OFFSET = "SET_OFFSET";
export const SET_QUERY = "SET_QUERY";
export const IS_LOADING = "IS_LOADING";

// CONTACTS
export const SET_CONTACTS = "SET_CONTACTS";
export const SET_CONTACT = "SET_CONTACT";
export const SET_CONTACT_LISTINGS = "SET_CONTACT_LISTINGS";
export const SET_CONTACT_GROUPS = "SET_CONTACT_GROUPS";
export const SET_EMAILS_BY_CONTACT = "SET_EMAILS_BY_CONTACT";

// LISTINGS
export const SET_LISTING = "SET_LISTING";
export const SET_LISTINGS = "SET_LISTINGS";
export const SET_LISTING_CONTACTS = "SET_LISTING_CONTACTS";
export const SET_EMAILS_BY_LISTING = "SET_EMAILS_BY_LISTING";

// GROUPS
export const SET_GROUPS = "SET_GROUPS";
export const SET_GROUP = "SET_GROUP";
export const SET_GROUP_CONTACTS = "SET_GROUP_CONTACTS";

// CAMPAIGNS:
export const SET_CAMPAIGN = "SET_CAMPAIGN";
export const SET_CAMPAIGNS = "SET_CAMPAIGNS";
export const SET_CAMPAIGN_LISTINGS = "SET_CAMPAIGN_LISTINGS";
export const SET_CAMPAIGN_RECIPIENTS = "SET_CAMPAIGN_RECIPIENTS";

// EMAILS
export const SET_EMAILS = "SET_EMAILS";
export const SET_EMAIL = "SET_EMAIL";
export const SET_EMAIL_QUERY = "SET_EMAIL_QUERY";
export const CLEAR_EMAILS = "CLEAR_EMAILS";
export const CLEAR_EMAIL = "CLEAR_EMAIL";
export const SET_EMAIL_SEARCH = "SET_EMAIL_SEARCH";

export const SET_IS_SEARCHING = "SET_IS_SEARCHING";
