version: '3'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    restart: 'always'
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    restart: 'always'

  redis:
    image: 'redis:3.2.10-alpine'
    ports:
      - '6379:6379'
    restart: 'always'
    volumes:
        - redis:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - 'redis'
      - 'postgres'
    command: nodemon --inspect index.js
    env_file:
      - '.env'
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=production
    restart: 'always'

volumes:
  redis: {}
