version: '3'

services:
  postgres:
    image: 'postgres:10.1-alpine'
    restart: 'always'
    ports:
      - '5432:5432'
    env_file:
      - '.env'


  web:
    build: .
    depends_on:
      - 'postgres'
    command: nodemon --inspect server
    env_file:
      - '.env'
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=production
