version: '3'

services:
  postgres:
    image: 'postgres:alpine'
    restart: 'always'
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    volumes:
    - 'postgres:/data'
    restart: 'always'

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    restart: 'always'


  web:
    build: .
    depends_on:
      - 'redis'
      - 'postgres'
    command: nodemon --inspect index.js
    env_file:
      - '.env'
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=production
    restart: 'always'

volumes:
  redis: {}
  postgres:
