module.exports = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  SESSION_SECRET: process.env.SESSION_SECRET,
  DB_USERNAME: RDS_USERNAME,
  DB_PASSWORD: process.env.RDS_PASSWORD,
  DB_NAME: process.env.RDS_DB_NAME,
  DB_HOST: proces.env.RDS_HOSTNAME,
  REDIS_URI: process.env.REDIS_URI
};
